const QUESTIONS = {
  vida: [
    { text: '¿Cuál es el recuerdo de infancia que más te define?' },
    { text: 'Si pudieras vivir en cualquier ciudad del mundo, ¿dónde y por qué?' },
    { text: '¿Qué harías si supieras que no puedes fallar?' },
    { text: '¿Cuál es la cosa más valiente que has hecho?' },
    { text: '¿Qué significa para ti una vida bien vivida?' },
    { text: '¿Tienes algo que nunca le has contado a nadie?' },
    { text: '¿Cuál es el momento en que más orgulloso/a te has sentido de ti mismo/a?' },
    { text: '¿Qué te enseñó tu mayor fracaso?' },
    { text: 'Si pudieras hablar con tu yo de 16 años, ¿qué le dirías?' },
    { text: '¿Cuál es tu mayor miedo y lo has enfrentado alguna vez?' },
    { text: '¿Qué cosa en tu vida querías que fuera diferente?' },
    { text: '¿Cuál sería tu día perfecto de principio a fin?' },
  ],
  valores: [
    { text: '¿Qué es lo que más valoras en una persona?' },
    { text: '¿Cómo es tu relación con tu familia?' },
    { text: '¿Cuándo fue la última vez que lloraste y por qué?' },
    { text: '¿Qué significa para ti la lealtad?' },
    { text: '¿Cómo reaccionas cuando alguien te decepciona?' },
    { text: '¿Tienes amistades de muchos años? ¿Qué las mantiene?' },
    { text: '¿Cómo sabes que estás enamorado/a?' },
    { text: '¿Cuál es tu lenguaje de amor principal?' },
    { text: '¿Qué necesitas de una pareja para sentirte seguro/a?' },
    { text: '¿Qué no perdonarías jamás en una relación?' },
    { text: '¿Eres de los que pelean o de los que evitan conflictos?' },
    { text: '¿Qué tan importante es tener espacio individual en una relación?' },
  ],
  dinero: [
    { text: '¿Eres más de ahorrar o de gastar? ¿Por qué?' },
    { text: '¿Tienes deudas ahora mismo?' },
    { text: '¿Ganas suficiente dinero para vivir como quieres?' },
    { text: '¿Pagarías la deuda de tu pareja si te lo pidiera?' },
    { text: '¿Cómo manejarías las finanzas en una relación seria — cuentas separadas, conjuntas o las dos?' },
    { text: '¿Has invertido en algo? ¿Cómo te fue?' },
    { text: '¿Qué tan importante es el dinero para tu felicidad?' },
    { text: '¿Tendrías un acuerdo prenupcial?' },
    { text: '¿Cuál ha sido tu peor decisión financiera?' },
    { text: '¿Pagarías la cuenta en la primera cita o dividirías?' },
    { text: '¿Tienes metas financieras claras para los próximos 5 años?' },
    { text: '¿Donarías el 10% de tus ingresos si pudieras?' },
  ],
  tabues: [
    { text: '¿Tienes una opinión impopular que defiendes de todas formas?' },
    { text: '¿Has hecho algo ilegal? ¿Qué fue?' },
    { text: '¿Qué tanto te importa lo que piensa la gente de ti?' },
    { text: '¿Has discriminado a alguien sin querer? ¿Cómo te diste cuenta?' },
    { text: '¿Qué tabú social crees que en realidad es completamente normal?' },
    { text: '¿Consumes o consumirías drogas recreativas? ¿En qué contexto?' },
    { text: '¿Cómo te llevas con la religión o espiritualidad?' },
    { text: '¿Hablarías de tu salud mental con una pareja desde el inicio?' },
    { text: '¿Qué tema evitas en conversaciones pero en realidad te importa mucho?' },
    { text: '¿Crees que la monogamia es natural o es una construcción social?' },
    { text: '¿Has mentido en una relación? ¿Qué tan grave fue?' },
    { text: '¿Qué tan abierto/a eres sobre tus traumas con una persona nueva?' },
  ],
  sexualidad: [
    { text: '¿Qué es lo más importante para ti en la intimidad física?' },
    { text: '¿Tienes fantasías que nunca has podido cumplir?' },
    { text: '¿Cómo sabes que alguien te atrae de verdad?' },
    { text: '¿Qué papel prefieres en la cama: tomar el control, cederlo o depende del momento?' },
    { text: '¿Has experimentado con ataduras o juegos de poder? ¿Cómo fue?' },
    { text: '¿Qué límites tienes en la intimidad que son completamente innegociables?' },
    { text: '¿Cuál es la diferencia para ti entre sexo y hacer el amor?' },
    { text: '¿Te atrae la idea de jugar con roles (dominante/sumiso)? ¿Por qué o por qué no?' },
    { text: '¿Qué tan importante es la compatibilidad sexual para que una relación funcione?' },
    { text: '¿Has usado juguetes o accesorios? ¿Qué te pareció?' },
    { text: '¿Tienes algo que jamás harías en la cama?' },
    { text: '¿Comunicarías tus deseos desde el inicio o preferirías irlo descubriendo?' },
  ],
};

module.exports = { QUESTIONS };
